FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
COPY apps/web/package*.json ./apps/web/
COPY services/runner/package*.json ./services/runner/
RUN npm install

COPY apps/web ./apps/web

WORKDIR /app/apps/web
EXPOSE 5173
CMD ["npm", "run", "dev"]
