export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#325f3f",
        "on-primary": "#ffffff",
        "primary-container": "#4a7856",
        "on-primary-container": "#cbfed4",
        "primary-fixed": "#bcefc5",
        "primary-fixed-dim": "#a1d2aa",
        "on-primary-fixed": "#00210d",
        "on-primary-fixed-variant": "#225031",
        secondary: "#a53a33",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe7c71",
        "on-secondary-container": "#721413",
        "secondary-fixed": "#ffdad6",
        "secondary-fixed-dim": "#ffb4ac",
        "on-secondary-fixed": "#410003",
        "on-secondary-fixed-variant": "#85221f",
        tertiary: "#7d4550",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#995d68",
        "on-tertiary-container": "#ffeeef",
        "tertiary-fixed": "#ffd9de",
        "tertiary-fixed-dim": "#fcb3bf",
        "on-tertiary-fixed": "#360c17",
        "on-tertiary-fixed-variant": "#6b3741",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#414941",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#3a6847",
        outline: "#717971",
        "outline-variant": "#c1c9bf",
        inverse: "#213145",
        "inverse-on-surface": "#eaf1ff",
        "inverse-primary": "#a1d2aa"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        gutter: "20px",
        base: "4px"
      },
      fontFamily: {
        "display-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "display-sm": ["30px", { lineHeight: "38px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600", letterSpacing: "-0.01em" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.02em" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500", letterSpacing: "0.03em" }]
      },
      boxShadow: {
        custom: "0 4px 6px -1px rgba(0, 0, 0, 0.05)"
      }
    }
  },
  plugins: []
};